module.exports = {
  blackCards: [
    "At school, I'm just Mandy. But at summer camp, I'm \"_____ Mandy.\"",
    "Beep beep! _____ coming through!",
    "Before I attend your sleepover, I must inform you: I prefer _____.",
    "Bow before me, for I am the Queen of _____!",
    "Boys? No. _____? Yes!",
    "Class, pay close attention. I will now demonstrate the physics of _____.",
    "Come on, Ethan. All the cool kids are doin' it. Wanna try _____?",
    "Come with me, and I will show you a world of _____.",
    "Coming soon! Batman vs. _____.",
    "Coming to theaters this holiday season, 'Star Wars: The Rise of _____.'",
    "Did you know that Benjamin Franklin invented _____?",
    "ENOUGH! I will not let _____ tear this family apart!",
    "Ethan is so good at _____!",
    "Ethan loves _____",
    "Ew. Grandpa smells like _____.",
    "Foolish child! Did you think you could escape from _____?",
    "Guys, stop it! There's nothing funny about _____.",
    "He who controls _____ controls the world.",
    "Hey guys. I just want to tell all my followers who are struggling with _____: it DOES get better.",
    "Hey, kids. I'm Sensei Todd. Today, I'm gonna teach you how to defend yourself against _____.",
    "I don't really know what my mom's job is, but I think it has something to do with _____.",
    "I got in trouble with my boss because I _____",
    "I hate my job because _____",
    "I lost my arm in a _____ accident.",
    "I went to the ER because of:",
    "Isn't this great, honey? Just you, me, the kids, and _____.",
    "Joey, look out behind you! It's _____!",
    "Ladies and gentlemen, I have discovered something amazing. I have discovered _____.",
    "Last night I dreamed about _____",
    "ME HUNGRY. ME WANT _____.",
    "Madam President, we've run out of time. The only option is _____.",
    "Me and my friends don't play with dolls anymore. We're into _____ now.",
    "Mom? You have to come pick me up! There's _____ at this party.",
    "Moms love _____.",
    "My dad and I enjoy _____ together.",
    "My favorite book is 'The Amazing Adventures of _____.'",
    "My favorite movie is _____",
    "My name is Peter Parker. I was bitten by a radioactive spider, and now I'm _____.",
    "Never fear, Captain _____ is here!",
    "Oh Dark Lord, we show out devotion with a humble offering of _____!",
    "Oh no! Siri, how do I fix _____?",
    "Oh, no thank you, Mrs. Lee. I've had plenty of _____ for now.",
    "One nation, under God, indivisible, with liberty and _____ for all.",
    "Outback Steakhouse: No rules. Just _____.",
    "Police! Arrest this man! He's _____!",
    "Run, run, as fast as you can! You can't catch me, I'm _____!",
    "Run, run, as fast as you can. You can't catch me, I'm _____!",
    "Shut up, Becky! At least I'm not _____.",
    "Thanks for watching! IF you want to see more vids of _____, smash that subscribe.",
    "The easiest way to tell me and my twin apart is that I have a freckle on my cheek and she's _____.",
    "There's nothing better than a peanut butter and _____ sandwich.",
    "They call me 'Mr._____.'",
    "Time to put on my favorite t-shirt, the one that says 'I heart _____.'",
    "We're off to see the wizard, the wonderful wizard of _____!",
    "Well, look at what we have here! A big fancy man walkin' like he's _____.",
    "What gets better with age?",
    "When I pooped, what came out?",
    "Where in the world is _____?",
    "Whoa there, partner! Looks like _____ spooked my horse.",
    "Why won't you love me anymore? Is it _____?",
    "You don't love me, Ethan. All you care about is _____.",
  ],
  whiteCards: [
    "14 cheeseburgers, 6 large fries, and a medium Sprite.",
    "A Democrat.",
    "A Republican.",
    "A baby boomer.",
    "A baby with a full mustache.",
    "A beard longer than 12 inches.",
    "A big sad dragon with no friends.",
    "A bird pooping on the president's head.",
    "A black hole.",
    "A bunch of dead squirrels on a trampoline.",
    "A butt that eats underwear.",
    "A corn dog.",
    "A cowboy who is half boy, half cow.",
    "A dead body.",
    "A dead whale.",
    "A fake kid made out of wood.",
    "A flamethrower.",
    "A hot air balloon powered by fart gas.",
    "A hundred screaming monkeys.",
    "A killer clown.",
    "A long, hot pee.",
    "A long, long snake.",
    "A naked lady in a painting.",
    "A nice, warm glass of pee.",
    "A pregnant person.",
    "A scoop of tuna.",
    "A screaming soccer dad.",
    "A super angry cat I found outside.",
    "A turd that just won't flush.",
    "A whole thing of cottage cheese.",
    "A wise, old woman with no teeth and cloudy eyes.",
    "Abraham Lincoln.",
    "An old, dirty cat with bad breath.",
    "An order of mozzarella sticks.",
    "An owl that hates you.",
    "Ariana Grande.",
    "Baby Yoda.",
    "Bad parenting.",
    "Barfing into a popcorn bucket.",
    "Batman.",
    "Becoming taller and stronger than Father.",
    "Becoming the president.",
    "Beer.",
    "Being French, hoh-hoh-hoh!",
    "Being adopted.",
    "Being dead.",
    "Being famous on YouTube.",
    "Being super serious right now.",
    "Bench pressing a horse.",
    "Gangster nation",
    "Big, juicy pimples.",
    "Big, slappy hands.",
    "Biting a rich person.",
    "Blasting farts in the powder room.",
    "Bleeding.",
    "Blossoming into a beautiful young man.",
    "Boys.",
    "Building a nuclear bunker at my parents' house.",
    "Burning books.",
    "Bursting into flames.",
    "Cat pee.",
    "Cavities.",
    "Cheetos fingers.",
    "Chest hair.",
    "Chinese campaign clothing.",
    "Chugging a lava lamp.",
    "Chunks.",
    "Cigarettes.",
    "Climate change.",
    "Coffee.",
    "Coming back from the dead.",
    "Covering myself with ketchup and mustard because I am a hot dog.",
    "Crying in the bathroom.",
    "Dad's meatloaf.",
    "Debating cartoon logic",
    "Diarrhea.",
    "Doing karate.",
    "Drinking a whole bottle of ranch.",
    "Drinking gasoline to see what it tastes like.",
    "Drinking out of the toilet and eating rubbish.",
    "Dying of old age.",
    "Eating a whole roll of toilet paper.",
    "Eating toenail clippings.",
    "Elegant party hats.",
    "Ethan",
    "Evil.",
    "Failure.",
    "Fake news.",
    "Falling into a pit of waffles.",
    "Farting a lot today.",
    "Farting, barfing, and passing out.",
    "Fat stacks of cash.",
    "Father's forbidden chocolates.",
    "Feasting upon human flesh.",
    "Finger teeth.",
    "Fire farts.",
    "Flamin' Hot Cheetos.",
    "Floating through the void of space and time.",
    "Flushing myself down the toilet.",
    "Forgetting to put on underwear.",
    "Tik Tok",
    "Garbage.",
    "Getting a girlfriend.",
    "Getting a skull tattoo.",
    "Getting crushed by a piano.",
    "Getting drunk.",
    "Getting married.",
    "Getting run over by a train.",
    "Getting scalded in the fave with hot beans.",
    "Getting skin cancer after 5 minutes at the beach",
    "Getting slapped with a fish.",
    "Getting struck in the toilet.",
    "Giggling and farting and slurping milkshakes.",
    "Going around sniffing people's armpits.",
    "Going ballistic",
    "Going beast mode.",
    "Grandpa.",
    "Happy Endings.",
    "Harry Potter.",
    "Having a baby.",
    "Having a really big head.",
    "Having many husbands.",
    "Having no bones.",
    "Having no friends.",
    "Having to pee so bad.",
    "Hogs.",
    "Horrible allergies.",
    "Hot, fresh turd.",
    "How much wood a woodchuck would chuck if a woodchuck could chuck wood.",
    "Huge pants.",
    "Hurting people's feelings.",
    "Idiots.",
    "Illegal drugs.",
    "Jesus's death.",
    "Josh.",
    "Knives.",
    "Legs.",
    "Lice.",
    "Licking a used band-aid.",
    "Lighting stuff on fire.",
    "Literally ruining my life.",
    "Living in a pineapple under the sea.",
    "Living in the dumpster.",
    "Mashing a banana into your belly button.",
    "Mayonnaise.",
    "Mean people",
    "Most of a horse.",
    "Moving to Ohio.",
    "Mowing the stupid lawn.",
    "My annoying brother.",
    "My annoying sister.",
    "My big donkey brother.",
    "My future husband.",
    "My girlfriend, who goes to another school.",
    "My sister's stupid boyfriend.",
    "Never showering.",
    "Nothing. Absolutely nothing.",
    "Nunchucks.",
    "Obama.",
    "Old people.",
    "One long hair growing out of a mole.",
    "One tough mama.",
    "One weird lookin' toe.",
    "Only beans.",
    "Pee-pee.",
    "Peeing in the cat's litter box.",
    "Peer pressure.",
    "Pizza.",
    "Playing trumpet for the mayor.",
    "Polka dot underwear",
    "Poo-poo.",
    "Pooping on the neighbor's lawn.",
    "Pork.",
    "Poseidon, Lord of the Sea.",
    "Putting my brain into the body of a tiger.",
    "Questioning authority.",
    "Respecting personal boundaries.",
    "Running away from home.",
    "Running full speed into a wall.",
    "SILENCE!",
    "Sacrificing Ethan.",
    "Satan.",
    "Screaming and screaming and never waking up.",
    "Screaming into a can of Pringles.",
    "Sharks.",
    "Shoplifting.",
    "Shrek.",
    "Shutting up.",
    "Sitting on a cake.",
    "Sitting on the toilet and going poop.",
    "Slowly turning into cheese.",
    "Smelling like onions.",
    "Social media.",
    "Some freakin' privacy.",
    "Soup.",
    "Space lasers.",
    "Spending my parent's hard-earned money.",
    "Spider-Man.",
    "Stank breath.",
    "Stealing people's money and going to jail.",
    "Swords.",
    "Taking a dump in the pool.",
    "Teaching a chicken to kill.",
    "The British.",
    "The baby.",
    "The babysitter.",
    "The beautiful potato.",
    "The bus driver.",
    "The divorce.",
    "The entire state of Texas.",
    "The first female President of the United States of America.",
    "The garbage man.",
    "The octopus stuck to my face.",
    "The oppressive system of capitalism.",
    "The police.",
    "The president.",
    "The way I feel when I see Ethan.",
    "The way grandpa smells.",
    "The wettest fart you ever heard.",
    "The whole family.",
    "This goat, who is my friend.",
    "This stupid game.",
    "Thousands of lasagna",
    "Throwing up double peace signs with my besties at Starbucks.",
    "Tossed salads and scrambled eggs.",
    "Total crap.",
    "Triangles.",
    "Trying to catch that dang raccoon.",
    "Twig and berries.",
    "Uncle Ethan.",
    "Unleashing a hell demon that will destroy our world.",
    "Urban legends",
    "Volleyball shorts.",
    "Whatever dad does at work.",
    "Your face.",
    "Your mom!",
    "Anne Cho",
    "Grace Huang",
    "The DLDPs",
    "Jia Ying",
    "Amelia Power",
    "The lazy interns",
    "The crazy software engineer",
    "Ugly UI/UX design",
    "Stupid websites",
    "Authentication",
  ],
};
